- client/client.go
- server/entitymanager/entitymanager.go
- server/server.go
- server/service/service.go
This PR adds verbose logging for all server and client activity.
> Add verbose logging for server and client activity

- .gitignore
This way they aren't included when staging changes for commits.
> Adding binary files to .gitignore

- proto/bootz.proto
This is to prevent namespace clashes in the bootz proto when we pull this code into g3
> Add package and remove whitespaces

- client/client.go
- server/entitymanager/entitymanager.go
- server/entitymanager/entitymanager_test.go
- server/server.go
- server/service/service.go
Generated protocol buffer packages must be renamed to remove underscores from their names, and their aliases must have a pb suffix.
> Correct import renaming for generated protobuf packages

- regenerate-files.sh
- server/entitymanager/testdata/chassis.prototxt
- testdata/inventory_local.prototxt
- testdata/wrong_inventory.prototxt
Also regenerate-files.sh script to build the entitymanager proto rules.
> Remove dhcp_config field from inventory data as it does not exist in the proto message.

- server/server_test.go
Starting the server this way caused issues with different goroutines logging things after the test had finished. Instead we just check that the server can be created. For a full end-to-end test of the server, we should set up integration tests intead.
> Don't actually start the server during the test.

- testdata/inventory_local.prototxt
Authz was fixed in https://github.com/openconfig/bootz/pull/50 however this one inventory file was not updated.
> Populate authz file location for local runs.

- common/ownership_voucher/ownership_voucher.go
type name will be used as ownershipvoucher.OwnershipVoucherInner by other packages, and that stutters; consider calling this Inner
> Rename OwnershipVoucherInner to Inner

- server/service/service.go
This prevents nil pointer deferences in general.
> Replace direct proto field access with getters. 

- common/signature/signature.go
The current message misidentifies the source of the error.
> Correct function name in error message.

- client/client.go
- common/owner_certificate/owner_certificate.go
- common/owner_certificate/owner_certificate_test.go
- server/entitymanager/entitymanager.go
- server/entitymanager/entitymanager_test.go
From https://www.rfc-editor.org/rfc/rfc8572.html#section-3.2, this field should be a CMS structure, not a PEM encoding.
> Return Owner Cert as a CMS structure instead of PEM encoding

- server/entitymanager/entitymanager.go
- server/entitymanager/entitymanager_test.go
- server/service/service.go
That map implementation limits us to how we look up entities and is hard to extend. This changes the inventory to just be a simple slice of entities.
> Refactor EntityManager to use a slice of Entities instead of a map.

- server/entitymanager/entitymanager.go
- server/entitymanager/entitymanager_test.go
- server/service/service.go
This field is not currently used in the open source implementation but will be once we migrate to using a single proto message in https://github.com/openconfig/bootz/issues/105. 
Additionally, the open source implementation does not need this field yet but the internal one does.
> Include resolved bpb.Chassis in GetBootstrapData method.

- server/service/service.go
- server/service/service_test.go
Currently there's no consistent way of looking up modular or fixed form factor chassis'. This is the first step in having a single entity lookup builder.
Note: This function isn't used yet, this will be plugged into service.go in a future PR.
> Add a new helper function "buildEntityLookup"

- server/entitymanager/entitymanager.go
- server/entitymanager/entitymanager_test.go
This removes the need for GetBootstrapData() to manually set the control card's status to UNSPECIFIED as it is already the default value.
> Allow SetStatus() to be called on unseen control cards

- server/entitymanager/entitymanager.go
- server/entitymanager/entitymanager_test.go
- server/service/service.go
Similar to https://github.com/openconfig/bootz/pull/118, we now rely on the resolved Chassis object instead of the lookup object in EntityManager.
> Pass the resolved Chassis object to Sign().

- common/ownership_voucher/ownership_voucher.go
- common/ownership_voucher/ownership_voucher_test.go
- testdata/artifacts.go
This supports the unmarshaling of XML OVs which is the encoding used by Juniper. Other vendors appear to use json as intended.
> Support XML encoding in addition to JSON for ownership vouchers.

- README.md
In current version of Bootz, enrollment and attestation happen after Bootz workflow is finished.
> Cleanup the contradictory wording

- dhcp/dhcp.go
- dhcp/main/dhcp.go
- dhcp/plugins/bootz/bootz.go
> Add support for rfc8572 DHCP option encoding.

- proto/bootz.proto
- server/entitymanager/entitymanager_test.go
- testdata/inventory.prototxt
- testdata/inventory_local.prototxt
Also updates the hash examples in the code.
> Update OS Image message with references to sZTP RFC

- server/service/service.go
Add a TODO to cleanup testing flag which is only required during vendor integrations.
> Add a TODO to cleanup the skip_enrollment flag

- server/service/service.go
This field will be used internally to differentiate between Edge and Core installations
> Add Domain field to Bootz chassis attributes

- proto/bootz.proto
```
* (M) proto/bootz.proto
- In some cases, the configuration that needs to be applied
through the boot process is not immutable per the current
specification of the bootz process. This change adds the
ability to provide dynamic configuration during an initial
boot that may be overwritten later in the process.
```
Consider the scenario that a device is being boostrapped from factory-reset (zero-ised) state. In such cases, the bootz server provides a `BootConfig` which contains the minimum manageable state of the device. This may include some configuration such as ACLs that protect the control-plane of the device. Currently, such an ACL becomes immutable, which means that to change it, a client needs to know that it must also call `gnoi.bootconfig.SetBootConfig` as well as `gnmi.Set` to …
> Add dynamic configuration to a `BootConfig` message.

- server/service/service.go
As of b/409157775 [google internal link] these fields are no longer used anywhere.
> Remove unused chassis fields

- .github/typos.toml
- testdata/cisco.cfg
As noted in #194, Cisco deprecates Type 7 password in newer releases (https://www.cisco.com/c/en/us/td/docs/iosxr/cisco8000/security/25xx/configuration/guide/b-system-security-cg-cisco8000-25xx/configuring-aaa-services.html#concept_lbt_ywl_g2c). 
This PR changes the cisco secret to option 10.  (a SHA512 value)
> Revise secret for cisco testdata
